import { Command } from "~/types";

export const goSiteCommands: Record<string, Command> = {
  github: {
    command: "github",
    title: "GitHub Profile",
    description: "View my open source contributions and projects",
    url: "https://github.com/clamstew",
    emoji: "🐙",
    tags: ["github", "open source"],
    type: "webpage-shortcut",
    status: "active",
  },
  "hire me": {
    command: "hire me",
    title: "LinkedIn Profile",
    description: "View my professional experience and contact info",
    url: "https://www.linkedin.com/in/claystewart/",
    emoji: "💼",
    tags: ["linkedin", "professional"],
    type: "webpage-shortcut",
    status: "active",
  },
  x: {
    command: "x",
    title: "X/Twitter Profile",
    description: "Follow me on X (formerly Twitter)",
    url: "https://x.com/Clay_Stewart",
    emoji: "🐦",
    tags: ["x", "twitter"],
    type: "webpage-shortcut",
    status: "active",
  },
  bsky: {
    command: "bsky",
    title: "Bluesky Profile",
    description: "Follow me on Bluesky",
    url: "https://bsky.app/profile/clay.codes",
    emoji: "☁️",
    tags: ["bluesky"],
    type: "webpage-shortcut",
    status: "active",
  },
  asdf: {
    command: "asdf",
    title: "ASDF Version Manager",
    description:
      "Tool version manager. (I thought it would be a funny response to a common thing someone would mess around and type.)",
    url: "https://github.com/asdf-vm/asdf",
    emoji: "🔧",
    tags: ["asdf", "version manager"],
    type: "webpage-shortcut",
    status: "unlisted",
  },
  "site code": {
    command: "site code",
    title: "Website Source",
    description: "View the source code for this website",
    url: "https://github.com/clamstew/next.clay.codes",
    emoji: "💻",
    tags: ["github", "open source"],
    type: "webpage-shortcut",
    status: "active",
  },
  notes: {
    command: "notes",
    title: "Notes App",
    description: "My notes application",
    url: "https://notes.build",
    emoji: "📝",
    tags: ["notes"],
    type: "webpage-shortcut",
    status: "active",
  },
  insulin: {
    command: "insulin",
    title: "Insulin Calculator",
    description: "Calculate insulin needs based on food intake",
    url: "https://fat-protein.netlify.app",
    emoji: "💉",
    tags: ["insulin", "calculator", "health", "tools", "entertainment"],
    type: "webpage-shortcut",
    status: "active",
  },
  shop: {
    command: "shop",
    title: "Online Shop",
    description: "My online store",
    url: "https://claycraftscode.myshopify.com",
    emoji: "🛍️",
    tags: ["shop"],
    type: "webpage-shortcut",
    status: "active",
  },
};
