import { Command } from "~/types";

export const terminalCommands: Record<string, Command> = {
  history: {
    command: "history",
    title: "Command History",
    description: "Show previously executed commands",
    emoji: "📜",
    tags: ["terminal", "history"],
    type: "terminal",
    status: "active",
  },
  fullscreen: {
    command: "fullscreen",
    title: "Fullscreen Mode",
    description: "Enter fullscreen mode",
    emoji: "🔍",
    tags: ["terminal", "fullscreen"],
    type: "terminal",
    status: "active",
  },
  minimize: {
    command: "minimize",
    title: "Minimize",
    description: "Exit fullscreen mode",
    emoji: "⬇️",
    tags: ["terminal", "fullscreen"],
    type: "terminal",
    status: "active",
  },
  terminal: {
    command: "terminal",
    title: "Terminal Mode",
    description: "Enter terminal mode with fullscreen",
    emoji: "🖥️",
    tags: ["terminal", "fullscreen"],
    type: "terminal",
    status: "active",
  },
  clear: {
    command: "clear",
    title: "Clear Screen",
    description: "Clear the terminal screen",
    emoji: "🧹",
    tags: ["terminal", "reset", "exit"],
    type: "terminal",
    status: "active",
  },
  exit: {
    command: "exit",
    title: "Exit",
    description: "Exit terminal mode",
    emoji: "🚪",
    tags: ["terminal", "reset", "exit"],
    type: "terminal",
    status: "active",
  },
  compgen: {
    command: "compgen",
    title: "List Commands",
    description: "Show all available commands",
    emoji: "📋",
    tags: ["terminal", "list"],
    type: "terminal",
    status: "active",
  },
  help: {
    command: "help",
    title: "Help",
    description: "Show help information for commands",
    emoji: "❓",
    tags: ["terminal", "help"],
    type: "terminal",
    status: "active",
  },
  "rm -rf": {
    command: "rm -rf",
    title: "Delete Everything",
    description: "Delete everything in the current directory",
    emoji: "💥",
    tags: ["terminal", "delete"],
    type: "terminal",
    status: "unlisted",
  },
};
